---
info:
  title: Guardian
  description: A lightweight authentication proxy for HTTP services
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/guardian
  x-cortex-tag: guardian
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: platform-delivery
openapi: 3.0.1
servers:
- url: "/"
